server:
  port: 8080
  tomcat:
    maxThreads: 500
    basedir: .
    accesslog:
      enabled: true
      pattern: "%t %a '%r' %s (%D ms)"

---
spring:
  profiles: dev
logging.config: classpath:logback-spring-dev.xml


---
spring:
  profiles: test
logging.config: classpath:logback-spring-test.xml

---
spring:
  profiles: prod
logging.config: classpath:logback-spring-prod.xml
